export const ACTION_SET_LOADING = "ACTION_SET_LOADING";
export const ACTION_LOAD_DETAILS = "ACTION_LOAD_DETAILS";
export const ACTION_UPDATE_DETAILS = "ACTION_UPDATE_DETAILS";
export const ACTION_SAVE_DETAILS = "ACTION_SAVE_DETAILS";
export const ACTION_SEND_EMAIL = "ACTION_SEND_EMAIL";
